const restaurans = [
  {
    id: "r1",
    name: "Coffee Mania",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Coffee",
  },
  {
    id: "r2",
    name: "Burger King",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Fast Food",
  },
  {
    id: "r3",
    name: "Mc Donalds",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Fast Food",
  },
  {
    id: "r4",
    name: "Maharaja Restaurant",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Indian Food",
  },
  {
    id: "r5",
    name: "Dera Restaurant",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Indian Food",
  },
  {
    id: "r6",
    name: "Hong Kong Chinese Restaurant",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Indian Food",
  },
  {
    id: "r7",
    name: "Papa Johns",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Pizza",
  },
  {
    id: "r8",
    name: "Dominos",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 09,
    type: "Pizza",
  },
];
