export const restaurants = [
  {
    id: "r1",
    name: "Coffee Mania",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Coffee",
    img: "/public/images/restaurants/coffee-mania.png",
    products: [
      {
        id: "p1",
        name: "Americano 200 ml",
        price: 2.5,
        quantity: 1,
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet, labore.",
        img: "/public/images/restaurants/coffee-mania.png",
      },
      {
        id: "p2",
        name: "Latte 200 ml",
        price: 2.5,
        quantity: 1,
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet, labore.",
        img: "/public/images/restaurants/coffee-mania.png",
      },
    ],
  },
  {
    id: "r2",
    name: "Burger King",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/burgur-king.svg",
    products: [
      {
        id: "p1",
        name: "Qrill Chicken Barbekyu",
        price: 6.9,
        quantity: 1,
        desc: "In this sandwich, grilled tender white chicken fillet is found, barbecue sauce, leaf lettuce, ripe tomato, thick mayonnaise and crispy fried onions on a toasted bun.",
        img: "../public/images/restaurants/qrill-chicken.avif",
      },
      {
        id: "p2",
        name: "Chessy Mary",
        price: 7.2,
        quantity: 1,
        desc: "Grilled chicken in combination with Cheddar cheese and Parmesan cheese, crispy onions, fresh vegetables and peerless Caesar dressing. Lots and lots of cheese!",
        img: "../public/images/restaurants/chessy-mary.avif",
      },
    ],
  },
  {
    id: "r3",
    name: "Mc Donalds",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/mc-dolands.png",
  },
  {
    id: "r4",
    name: "Maharaja",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Indian Food",
    img: "../public/images/restaurants/maharaja.jpg",
  },
  {
    id: "r5",
    name: "Dera Restaurant",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Indian Food",
    img: "../public/images/restaurants/dera.jpg",
  },
  {
    id: "r6",
    name: "Hong Kong",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Chinese Food",
    img: "../public/images/restaurants/hong-kong.jpg",
  },
  {
    id: "r7",
    name: "Papa Johns",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/papa-johns.svg",
  },
  {
    id: "r8",
    name: "Dominos",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/dominos.png",
  },
];
