export const restaurants = [
  {
    id: "r1",
    name: "Coffee Mania",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Coffee",
    img: "/public/images/restaurants/coffee-mania.png",
    products: [
      {
        id: "p1",
        name: "cappucino",
        price: 5,
        quantity: 1,
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet, labore.",
        img: "/public/images/restaurants/coffee-mania.png",
      },
      {
        id: "p2",
        name: "cappucino",
        price: 5,
        quantity: 1,
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet, labore.",
        img: "/public/images/restaurants/coffee-mania.png",
      },
    ],
  },
  {
    id: "r2",
    name: "Burger King",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/burgur-king.svg",
    products: [
      {
        id: "p1",
        name: "Burger KIng",
        price: 5,
        quantity: 1,
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet, labore.",
        img: "../public/images/restaurants/burgur-king.svg",
      },
      {
        id: "p2",
        name: "cappucino",
        price: 5,
        quantity: 1,
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet, labore.",
        img: "../public/images/restaurants/burgur-king.svg",
      },
    ],
  },
  {
    id: "r3",
    name: "Mc Donalds",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/mc-dolands.png",
  },
  {
    id: "r4",
    name: "Maharaja",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Indian Food",
    img: "../public/images/restaurants/maharaja.jpg",
  },
  {
    id: "r5",
    name: "Dera Restaurant",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Indian Food",
    img: "../public/images/restaurants/dera.jpg",
  },
  {
    id: "r6",
    name: "Hong Kong",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Chinese Food",
    img: "../public/images/restaurants/hong-kong.jpg",
  },
  {
    id: "r7",
    name: "Papa Johns",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/papa-johns.svg",
  },
  {
    id: "r8",
    name: "Dominos",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/dominos.png",
  },
];
